"""empty message

Revision ID: 5024bf1874b5
Revises: ed382107770a
Create Date: 2021-08-11 10:23:53.874725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5024bf1874b5'
down_revision = 'ed382107770a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_unit', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_unit', 'active')
    # ### end Alembic commands ###
