"""empty message

Revision ID: 7a3b3ab82c3a
Revises: 88d95b4ffba5
Create Date: 2021-08-12 17:18:46.636741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3b3ab82c3a'
down_revision = '88d95b4ffba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('item', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('item_category', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('item_category', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('item_unit', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('item_unit', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('room', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('room', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('room_members', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('room_members', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('room_members', sa.Column('room_name', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('user', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_by')
    op.drop_column('user', 'created_by')
    op.drop_column('room_members', 'room_name')
    op.drop_column('room_members', 'updated_by')
    op.drop_column('room_members', 'created_by')
    op.drop_column('room', 'updated_by')
    op.drop_column('room', 'created_by')
    op.drop_column('item_unit', 'updated_by')
    op.drop_column('item_unit', 'created_by')
    op.drop_column('item_category', 'updated_by')
    op.drop_column('item_category', 'created_by')
    op.drop_column('item', 'updated_by')
    op.drop_column('item', 'created_by')
    # ### end Alembic commands ###
