"""empty message

Revision ID: ed382107770a
Revises: 
Create Date: 2021-08-11 10:03:14.377431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed382107770a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_category',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.Integer(), nullable=True),
    sa.Column('category_no', sa.String(length=20), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_no', name='unique_constraint_categoryno')
    )
    op.create_table('item_unit',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.Integer(), nullable=True),
    sa.Column('unit_no', sa.String(length=20), nullable=False),
    sa.Column('unit_name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_no', name='unique_constraint_unitno')
    )
    op.create_table('item',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.Integer(), nullable=True),
    sa.Column('item_no', sa.String(length=20), nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('extra_attributes', sa.JSON(), nullable=True),
    sa.Column('item_category_id', sa.String(length=50), nullable=True),
    sa.Column('item_unit_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['item_category_id'], ['item_category.id'], ),
    sa.ForeignKeyConstraint(['item_unit_id'], ['item_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_no', name='unique_constraint_itemno')
    )
    op.create_index(op.f('ix_item_item_category_id'), 'item', ['item_category_id'], unique=False)
    op.create_index(op.f('ix_item_item_unit_id'), 'item', ['item_unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_item_unit_id'), table_name='item')
    op.drop_index(op.f('ix_item_item_category_id'), table_name='item')
    op.drop_table('item')
    op.drop_table('item_unit')
    op.drop_table('item_category')
    # ### end Alembic commands ###
